services:
  1mcloud:
    build: .
    container_name: 1mcloud_dev
    restart: unless-stopped
    env_file:
      - server/.env
    networks:
      - shared_infra
    ports:
      - "3002:3002"

networks:
  shared_infra:
    external: true
